stages:
  - build
  - test
  - docker

variables:
  PROJECT_DIR: part_1_disease
  BUILD_DIR: $PROJECT_DIR/build
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# Use Docker image with build tools and CMake
image: docker:24.0.5

services:
  - docker:24.0.5-dind

before_script:
  - apk add --no-cache git cmake build-base

build_project:
  stage: build
  script:
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR
    - cmake ..
    - make
  artifacts:
    paths:
      - $BUILD_DIR/hpc_disease_simulation
      - $BUILD_DIR/test
    expire_in: 1 hour

run_tests:
  stage: test
  needs: ["build_project"]
  script:
    - chmod +x $BUILD_DIR/test
    - ./$BUILD_DIR/test --reporter junit --out $BUILD_DIR/test-report.xml
  artifacts:
    reports:
      junit: $BUILD_DIR/test-report.xml
    paths:
      - $BUILD_DIR/test-report.xml
    expire_in: 1 hour

docker_build:
  stage: docker
  needs: ["build_project"]
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_TAG $PROJECT_DIR
    - docker push $IMAGE_TAG
  only:
    - main
